### ISSUE TITLE
DjangoListField using field_name and covering up a model field still accesses the original model field

### ISSUE THREAD

**Issue by farcepest** [MrThearMan/graphene-django-query-optimizer#136]
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.8.5

### Which python version are you using?

3.10

### What operating system are you on?

Ubuntu

### Description

I have a Django model which looks something like this:

```
class Lead(models.Model):
   ...
   contacts = models.ManyToManyField("Contact", through="LeadContact")
   ...

class LeadContact(models.Model):
    ...
    lead = models.ForeignKey("Lead")
    contact = models.ForeignKey("Contact")
    ...

class Contact(models.Model):
    ...
    # typical contact stuff not relevant
    ...
```

In my pre-existing graphql setup, I had something like this:

```
class LeadType(DjangoObjectType):
    class Meta:
        model = Lead

    ...
    contacts = List(LeadContactType)
    ...

    def resolver_contacts(root, info):
        return root.leadcontact_set.all()

```
IOW, I was exposing the lead-to-contact through table (leadcontact_set) through graphql as contacts, so that contacts would be a [LeadContactType], which would then contain [ContactType] and some other metadata. This is primarily for cosmetic reasons (leadcontact_set is ugly).

Trying to switch this over to graphene-django-query-optimizer:

```
from query_optimizer import DjangoObjectType, DjangoListField

class LeadType(DjangoObjectType):
    class Meta:
        model = Lead

    ...
    contacts = DjangoListField(LeadContactType, field_name="leadcontact_set")
    ...

```
Unfortunately this fails: The contacts fields returns [Contact] (which graphql raises an error because it's not a LeadContact). It seems like the contacts Field is still accessing the model contacts field, which returns Contact instances. Adding "contacts" to the Meta.exclude didn't help; it raised a warning about excluding a field which was defined as a custom field had no effect, and otherwise the same results. It seems DjangoListField is still accessing contacts despite the use of field_name.

On top of this, it causes some really bad queries which aren't used, such as one which selects all lead contacts WHERE lead_id IN [...every lead id in the system]. Witnessed with Django Debug Toolbar.

I could maybe work around this by renaming the current graphql contacts field to lead_contacts, but would prefer not to rename this field in my existing API.

Otherwise, the queries I'm getting are perfect AFAIK, and thanks.

**Comment by farcepest** [comment]
Well, probably obvious to you, but I had simply forgotten to have resolve_contacts method (or rather had deleted earlier one).

**Comment by farcepest** [comment]
OK, after even further testing, it still appears this is a bug, even with adding a resolve_contacts method. (Typo in original description has resolver_contacts). I might need to make a test case for this to demonstrate.

**Comment by MrThearMan** [comment]
Hi! Thanks for the issue.

Looking into this, unfortunately I don't think Django allows this kind of optimization. Specifically, you are trying to override the `contacts` attribute of the `Lead` model with prefeched `LeadContact` models, which is not possible.

Optimization of `one-to-many` and `many-to-many` models to different attributes works through `Prefetch(..., to_attr="<new_attr>")` mechanism, so effectively the query that would be generated is something like this.

```python
Lead.objects.all().prefetch_related(
    Prefetch(
        "leadcontact_set", 
        LeadContact.objecs.all(), 
        to_attr="contacts",
    ),
)
```

I've tried this with a similar setup I have in my test project for this library with `Owner` <- `Ownership` -> `Sale`, so the above might be slightly incorrect, but if you run this and check that `contacts` is, it will still contain `Contact` entities. This is because `Lead.contacts` is a `ManyToManyDescriptor`, which you cannot override with values from the queryset. It's odd that there is no error, but it doesn't work nontheless.

So, I suggest that you rename the field to `lead_contacts` so that the optimization is possible.

---

> _On top of this, it causes some really bad queries which aren't used, such as one which selects all lead contacts WHERE lead_id IN [...every lead id in the system]. Witnessed with Django Debug Toolbar._

I'm guessing this is due to you using `DjangoListField` and not `DjangoConnectionField`. The list field just does a regular prefetch, which is django works with those `IN [...every related id in the system]` queries. You are also likely to hit your databases [Maximum number of parameters](https://www.sqlite.org/limits.html#:~:text=Maximum%20Number%20Of%20Host%20Parameters%20In%20A%20Single%20SQL%20Statement) limit for larger prefetches through this. Therefore, if you have a large amount of relations in a subfield, I suggest using `DjangoConnectionField`, although it does require the use of the Relay pagination protocol.

---

If you have any other questions, feel free to post here, but I'll close the issue in the meantime.
